### ISSUE TITLE
Error with effects from mods

### ISSUE THREAD

**Issue by happykgit** [Gakuto1112/SenkoSan#22]
I'm play with mod Alex's mobs and whenever I get effect from this mod i get an Error and model resets strangely

![Error](https://github.com/Gakuto1112/SenkoSan/assets/169473266/0a994148-37ac-4d3a-ad43-bc1da4981fba)

**Comment by Gakuto1112** [comment]
Thanks for your report!
First, I wrote the following in the readme:

> This avatar is designed for work with no resource pack and no other mods are installed. An unexpected issue may occurs when you use it with any resource packs and mods (texture and armor inconsistencies, etc.).However, I won't support in these cases.

However, there is no good thing if I reject your report, so I will do it later.

**Comment by Gakuto1112** [comment]
This issue has been fixed. A new version will be released soon.

Thank you for your report!
