### ISSUE TITLE
Senko does not frighten.

### ISSUE THREAD

**Issue by Furnnya** [Gakuto1112/SenkoSan#24]
Senko does not frighten when afflicted with Darkness or a Warden is near her. 
![Screenshot_36](https://github.com/user-attachments/assets/9dbba1dc-85e9-4b34-8d5d-d459a4be712f)

Neither does she summon fox fires when under night vision.
![Screenshot_37](https://github.com/user-attachments/assets/69a78b77-2b75-48ca-9b93-bfb7ce471679)

This was on a no-mods, no resource-pack Vanilla Minecraft World on FORGE 1.20.1, running 0.1.4 Figura.

**Comment by Furnnya** [comment]
This also extends to her Darkness effect sleeping pose.
It does not work, or do anything different than the normal sleeping.

**Comment by Gakuto1112** [comment]
Thank you for your report!
I just confirmed this issue. I will fix it.

**Comment by Gakuto1112** [comment]
This issue has been fixed at v1.25.7.
If you are still facing an issue. Please comment this.
