### ISSUE TITLE
防具装飾が消えない

### ISSUE THREAD

**Issue by Gakuto1112** [Gakuto1112/SenkoSan#7]
> one thing I noticed, armor trims show up even if the avatar has "show armor" disabled.

防具を非表示にしても、防具装飾が消えない模様

https://discord.com/channels/1129805506354085959/1130085547621224468/1134639024527654912

![image](https://github.com/Gakuto1112/SenkoSan/assets/90630001/26435e0a-53c2-44c1-ae03-2b6fa973ac4c)

**Comment by Gakuto1112** [comment]
現在このバグの再現方法不明

**Comment by Gakuto1112** [comment]
取りあえず動画を撮ってもらったがこれでもよく分からん

https://cdn.discordapp.com/attachments/1130085547621224468/1134719828830191616/javaw_6QW1BA2q1i.mp4

**Comment by Gakuto1112** [comment]
取りあえずデバッグ出力を追加したアバターを送信してそれで様子見

**Comment by moonfraiy** [comment]
hi how i get a Minecraft skin in free Unblocked minecraft

**Comment by Gakuto1112** [comment]
> hi how i get a Minecraft skin in free Unblocked minecraft

What do you mean "free Unblocked minecraft"?
And you should not ask it here. You should post new discussion in [Issue](https://github.com/Gakuto1112/SenkoSan/issues) or [Discussion](https://github.com/Gakuto1112/SenkoSan/discussions).
In this case, it seems not to be a issue, so you should post it in [Discussion](https://github.com/Gakuto1112/SenkoSan/discussions).

**Comment by Gakuto1112** [comment]
再現不可のためクローズ
